MVCForum.Website/Areas/Admin/ViewModels/AdminCategoryViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using DataAnnotationsExtensions;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.Areas.Admin.ViewModels
{
    public class ListCategoriesViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
    }

    public class CreateCategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        [DisplayName("Category Name")]
        [Required]
        [StringLength(600)]
        public string Name { get; set; }

        [DisplayName("Category Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Lock The Category")]
        public bool IsLocked { get; set; }

        [DisplayName("Sort Order")]
        [Numeric]
        public int SortOrder { get; set; }

        [DisplayName("Parent Category")]
        public Guid? ParentCategory { get; set; }

        public List<Category> AllCategories { get; set; } 
    }

    public class EditCategoryViewModel
    {
        [DisplayName("Category Name")]
        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        [DisplayName("Category Description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [DisplayName("Lock The Category")]
        public bool IsLocked { get; set; }

        [DisplayName("Sort Order")]
        [Numeric]
        public int SortOrder { get; set; }

        [HiddenInput]
        public Guid Id { get; set; }

        [HiddenInput]
        public DateTime DateCreated { get; set; }

        [HiddenInput]
        public string NiceUrl { get; set; }

        [DisplayName("Parent Category")]
        public Guid? ParentCategory { get; set; }

        public List<Category> AllCategories { get; set; } 
    }

    public class DeleteCategoryViewModel
    {
        [HiddenInput]
        public Guid Id { get; set; }

        public Category Category { get; set; }

        public List<Category> SubCategories { get; set; }
    }
}

MVCForum.Website/Areas/Admin/Controllers/AdminCategoryController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.Areas.Admin.ViewModels;

namespace MVCForum.Website.Areas.Admin.Controllers
{
    [Authorize(Roles = AppConstants.AdminRoleName)]
    public class AdminCategoryController : BaseAdminController
    {
        private readonly ICategoryService _categoryService;

        public AdminCategoryController(ILoggingService loggingService,
                                        IUnitOfWorkManager unitOfWorkManager,
                                       IMembershipService membershipService,
                                       ILocalizationService localizationService,
                                       ICategoryService categoryService,
                                       ISettingsService settingsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, settingsService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [ChildActionOnly]
        public PartialViewResult ListAllCategories(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListCategoriesViewModel
                                    {
                                        Categories = _categoryService.GetAllSubCategories(id)
                                    };
                return PartialView(viewModel);
            }
        }

        [ChildActionOnly]
        public PartialViewResult GetMainCategories()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var viewModel = new ListCategoriesViewModel
                                    {
                                        Categories = _categoryService.GetAll().OrderBy(x => x.SortOrder)
                                    };
                return PartialView(viewModel);
            }
        }

        [ChildActionOnly]
        public PartialViewResult CreateCategory()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var categoryViewModel = new CreateCategoryViewModel {AllCategories = _categoryService.GetAll().ToList()};
                return PartialView(categoryViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(CreateCategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var category = new Category
                                           {
                                               Name = categoryViewModel.Name,
                                               Description = categoryViewModel.Description,
                                               IsLocked = categoryViewModel.IsLocked,
                                               SortOrder = categoryViewModel.SortOrder,
                                           };
                       
                        if (categoryViewModel.ParentCategory != null)
                        {
                            category.ParentCategory =
                                _categoryService.Get(categoryViewModel.ParentCategory.Value);
                        }

                        _categoryService.Add(category);

                        // We use temp data because we are doing a redirect
                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                        {
                                                                            Message = "Category Created",
                                                                            MessageType =
                                                                                GenericMessages.success
                                                                        };
                        unitOfWork.Commit();
                    }
                    catch (Exception)
                    {
                        unitOfWork.Rollback();
                    }
                }
            }
            
            return RedirectToAction("Index");
        }
    

    public ActionResult EditCategory(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var category = _categoryService.Get(id);
                var categoryViewModel = new EditCategoryViewModel
                                            {
                                                Name = category.Name,
                                                Description = category.Description,
                                                IsLocked = category.IsLocked,
                                                SortOrder = category.SortOrder,
                                                Id = category.Id,
                                                DateCreated = category.DateCreated,
                                                NiceUrl = category.NiceUrl,
                                                ParentCategory = category.ParentCategory == null ? Guid.Empty : category.ParentCategory.Id,
                                                AllCategories = _categoryService.GetAll()
                                                    .Where(x => x.Id != category.Id)
                                                    .ToList(),
                                            };

                return View(categoryViewModel);
            }
        }

        [HttpPost]
        public ActionResult EditCategory(EditCategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    try
                    {
                        var category = _categoryService.Get(categoryViewModel.Id);

                        category.Description = categoryViewModel.Description;
                        category.IsLocked = categoryViewModel.IsLocked;
                        category.Name = categoryViewModel.Name;
                        category.SortOrder = categoryViewModel.SortOrder;

                        if (categoryViewModel.ParentCategory != null)
                        {
                            category.ParentCategory = _categoryService.Get(categoryViewModel.ParentCategory.Value);
                        }
                        else
                        {
                            // Must access property (trigger lazy-loading) before we can set it to null (Entity Framework bug!!!)
                            var triggerEfLoad = category.ParentCategory;
                            category.ParentCategory = null;
                        }

                        _categoryService.UpdateSlugFromName(category);

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                        {
                                                                            Message = "Category Updated",
                                                                            MessageType = GenericMessages.success
                                                                        };

                        unitOfWork.Commit();
                    }
                    catch (Exception ex)
                    {
                        LoggingService.Error(ex);
                        unitOfWork.Rollback();

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = "Category Update Failed",
                            MessageType = GenericMessages.error
                        };
                    }
                }
            }

            return View("PopupConfirm");
        }

        public ActionResult DeleteCategoryConfirmation(Guid id)
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var cat = _categoryService.Get(id);
                var subCats = _categoryService.GetAllSubCategories(id).ToList();
                var viewModel = new DeleteCategoryViewModel
                                    {
                                        Id = cat.Id,
                                        Category = cat,
                                        SubCategories = subCats
                                    };

            return View(viewModel);
            }
        }

        public ActionResult DeleteCategory(Guid id)
        {
            using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
            {
                try
                {
                    var cat = _categoryService.Get(id);
                    _categoryService.Delete(cat);
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                                                                    {
                                                                        Message = "Category Deleted",
                                                                        MessageType = GenericMessages.success
                                                                    };

MVCForum.Website/Areas/Admin/Views/AdminCategory/CreateCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.CreateCategoryViewModel


@section AdminHeader
{
        @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )  
}


@using (Html.BeginForm("CreateCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Create New Category</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.IsLocked)
            @Html.LabelFor(model => model.IsLocked)
            @Html.ValidationMessageFor(model => model.IsLocked)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.ParentCategory)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ParentCategory, new SelectList(Model.AllCategories, "id", "Name"), string.Empty)
            @Html.ValidationMessageFor(model => model.ParentCategory)
        </div>

        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="Create" />
        </div>
    </fieldset>
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/DeleteCategoryConfirmation.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.DeleteCategoryViewModel

@{
    ViewBag.Title = "Delete Category";

    if (Model.SubCategories.Any())
    {
        <h2>Unable To Delete</h2>
        <p>This category has sub categories, please re-assign them to new parent categories first</p>
        
        <h4>Sub Categories</h4>
        <ul>
            @foreach (var subCat in Model.SubCategories)
            {
                <li><strong>@subCat.Name</strong></li>
            }
        </ul>
        
        <a href="@Url.Action("Index")" class="btn btn-large btn-success">Back</a>
    }
    else if (Model.Category.Topics.Any())
    {
        <h2>Unable To Delete</h2>
        <p>This category has discussions associated with it, please either delete or move the topics to a different category</p>
        
        <h4>Topics</h4>
        <ul>
            @foreach (var topic in Model.Category.Topics)
            {
                <li><a href="@topic.NiceUrl">@topic.Name</a></li>
            }
        </ul>
        
        <a href="@Url.Action("Index")" class="btn btn-large btn-success">Back</a>
    }
    else
    {
        using (Html.BeginForm("DeleteCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <h2>Delete Category?</h2>        
            <p>Are you sure you want to delete this Category</p>
            @Html.HiddenFor(x => x.Id)
            <div class="submit-holder">
                <input type="submit" class="btn btn-large btn-success" value="Yes" /> 
            </div>
        }
    }
}     

MVCForum.Website/Areas/Admin/Views/AdminCategory/EditCategory.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.EditCategoryViewModel

@{
    Layout = "~/Areas/Admin/Views/shared/_AdminBlankLayout.cshtml";
    ViewBag.Title = "Edit Category";    
}

@section AdminHeader
{
        @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )  
}

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Edit Category</legend>
        
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.DateCreated) 
        @Html.HiddenFor(model => model.NiceUrl)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-field n3ocheckboxfield">
            @Html.EditorFor(model => model.IsLocked)
            @Html.LabelFor(model => model.IsLocked)
            @Html.ValidationMessageFor(model => model.IsLocked)
        </div>       

        <div class="editor-label">
            @Html.LabelFor(model => model.SortOrder)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SortOrder)
            @Html.ValidationMessageFor(model => model.SortOrder)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentCategory)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.ParentCategory, new SelectList(Model.AllCategories, "id", "Name"), string.Empty)
            @Html.ValidationMessageFor(model => model.ParentCategory)
        </div>

        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="Update" />
        </div>
    </fieldset>
}

MVCForum.Website/Areas/Admin/Views/AdminCategory/GetMainCategories.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.ListCategoriesViewModel
@{
    var mainCategories = Model.Categories.Where(x => x.ParentCategory == null).ToList();
    var subCategories = Model.Categories.Where(x => x.ParentCategory != null).ToList();
}


        
    @if (mainCategories.Any())
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Main Categories
                    </th>
                    <th>Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cat in mainCategories)
                { 
                    <tr>
                        <td class="editcategory mainadmincategory">
                            <a href="@Url.Action("EditCategory", new { id = cat.Id })" class="catfancybox">@Html.Raw(cat.Name)</a>
                        </td>
                        <td>
                            <a href="@Url.Action("DeleteCategoryConfirmation", new { id = cat.Id })" title="Delete @Html.Raw(cat.Name)" class="btn btn-small"><i class="icon-remove"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    @if (subCategories.Any())
    {
        <h2>Sub Categories</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Sub Categories
                    </th>
                    <th>Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cat in subCategories)
                { 
                    <tr>
                        <td class="editcategory subadmincategory">
                            <a href="@Url.Action("EditCategory", new { id = cat.Id })" class="catfancybox">@Html.Raw(cat.Name)</a>
                        </td>
                        <td>
                            <a href="@Url.Action("DeleteCategoryConfirmation", new { id = cat.Id })" title="Delete @Html.Raw(cat.Name)" class="btn btn-small"><i class="icon-remove"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }



MVCForum.Website/Areas/Admin/Views/AdminCategory/Index.cshtml
@{
    ViewBag.Title = "Manage Categories";
}

@section AdminHeader
{
    <script type="text/javascript">
        // Can also use beforeClose ?
        $('.catfancybox').fancybox({
            type: 'iframe',
            padding: 15,
            afterClose: function () {
                parent.location.reload(true);
            }
        });
    </script>
}

<div class="row-fluid">
    <div class="span12">
        @Html.Action("GetMainCategories")
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        @Html.Action("CreateCategory")
    </div>
</div>


MVCForum.Website/Areas/Admin/Views/AdminCategory/ListAllCategories.cshtml
@model MVCForum.Website.Areas.Admin.ViewModels.ListCategoriesViewModel

@{
    if(Model.Categories.Any())
    {
        <ul class="subcategorylist">
        @foreach (var cat in Model.Categories)
        {
            <li class="subcategoryitem"><a href="@Url.Action("EditCategory", new {id = cat.Id})" class="catfancybox">@Html.Raw(cat.Name)</a>
            <a href="@Url.Action("DeleteCategoryConfirmation", new {id = cat.Id})"><img src="/Content/admin/Images/icons/cross.png" alt="Delete" title="Delete @Html.Raw(cat.Name)" /></a></li>
            @Html.Action("ListAllCategories", new { id = cat.Id })
        }
        </ul>
    }
}



MVCForum.Website/Areas/Admin/Views/AdminCategory/PopupConfirm.cshtml
@{
    Layout = "~/Areas/Admin/Views/shared/_AdminBlankLayout.cshtml";
}

<script type="text/javascript">
    $(function () {
        parent.delay(800).$.fancybox.close();
    });
</script>