MVCForum.Website/ViewModels/SearchViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVCForum.Domain.DomainModel;

namespace MVCForum.Website.ViewModels
{
    public class SearchViewModel
    {
        public PagedList<Topic> Topics { get; set; }
        public Dictionary<Category, PermissionSet> AllPermissionSets { get; set; }
        public string Term { get; set; }

        public int? PageIndex { get; set; }
        public int? TotalCount { get; set; }
    }
}

MVCForum.Website/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OAuth2;
using DotNetOpenAuth.OpenId.Extensions.AttributeExchange;
using DotNetOpenAuth.OpenId.RelyingParty;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.OpenAuth;
using MVCForum.OpenAuth.Facebook;
using MVCForum.Utilities;
using MVCForum.Website.Areas.Admin.ViewModels;
using MVCForum.Website.ViewModels;
using MembershipCreateStatus = MVCForum.Domain.DomainModel.MembershipCreateStatus;
using MembershipUser = MVCForum.Domain.DomainModel.MembershipUser;

namespace MVCForum.Website.Controllers
{
    public class MembersController : BaseController
    {
        private readonly IPostService _postService;
        private readonly IReportService _reportService;
        private readonly IEmailService _emailService;
        private readonly IPrivateMessageService _privateMessageService;
        private readonly IBannedEmailService _bannedEmailService;
        private readonly IBannedWordService _bannedWordService;

        private MembershipUser LoggedOnUser;
        private MembershipRole UsersRole;

        private InMemoryTokenManager _tokenManager;

        public MembersController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService,
            IRoleService roleService, ISettingsService settingsService, IPostService postService, IReportService reportService, IEmailService emailService, IPrivateMessageService privateMessageService, IBannedEmailService bannedEmailService, IBannedWordService bannedWordService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _reportService = reportService;
            _emailService = emailService;
            _privateMessageService = privateMessageService;
            _bannedEmailService = bannedEmailService;
            _bannedWordService = bannedWordService;

            LoggedOnUser = UserIsAuthenticated ? MembershipService.GetUser(Username) : null;
            UsersRole = LoggedOnUser == null ? RoleService.GetRole(AppConstants.GuestRoleName) : LoggedOnUser.Roles.FirstOrDefault();
        }

        #region Common Methods

        private bool ProcessSocialLogonUser(MembershipUser user, bool doCommit)
        {
            // Secondly see if the email is banned
            if (_bannedEmailService.EmailIsBanned(user.Email))
            {
                doCommit = false;
                TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                {
                    Message = LocalizationService.GetResourceString("Error.EmailIsBanned"),
                    MessageType = GenericMessages.error
                };
            }
            else
            {
                // Check not already someone with that user name, if so append count
                var exists = MembershipService.GetUser(user.UserName);
                if (exists != null)
                {
                    var howMany = MembershipService.SearchMembers(user.UserName, int.MaxValue);
                    user.UserName = string.Format("{0} ({1})", user.UserName, howMany != null ? howMany.Count : 1);
                }

                // Now check settings, see if users need to be manually authorised
                var manuallyAuthoriseMembers = SettingsService.GetSettings().ManuallyAuthoriseNewMembers;
                var memberEmailAuthorisationNeeded = SettingsService.GetSettings().NewMemberEmailConfirmation ?? false;
                if (manuallyAuthoriseMembers || memberEmailAuthorisationNeeded)
                {
                    user.IsApproved = false;
                }

                var createStatus = MembershipService.CreateUser(user);
                if (createStatus != MembershipCreateStatus.Success)
                {
                    doCommit = false;
                    TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                    {
                        Message = MembershipService.ErrorCodeToString(createStatus),
                        MessageType = GenericMessages.error
                    };
                }
                else
                {
                    // Set the view bag message here
                    SetRegisterViewBagMessage(manuallyAuthoriseMembers, memberEmailAuthorisationNeeded, user);
                }
            }

            return doCommit;
        }

        #endregion

        #region Social Logons

        private void InstantiateTwitterInMemoryTokenManager()
        {
            var twitterAppId = ConfigUtils.GetAppSetting("TwitterAppId");
            var twitterAppSecret = ConfigUtils.GetAppSetting("TwitterAppSecret");

            // Only instantiate if the twitter credentials are not null
            if (!string.IsNullOrEmpty(twitterAppId) && !string.IsNullOrEmpty(twitterAppSecret))
            {
                _tokenManager = new InMemoryTokenManager(twitterAppId, twitterAppSecret);
            }
        }

        public ActionResult LogonTwitter()
        {
            InstantiateTwitterInMemoryTokenManager();
            var client = new TwitterClient(_tokenManager, Url.Action("TwitterCallback"));
            client.StartAuthentication();
            return null;
        }

        public ActionResult TwitterCallback()
        {
            InstantiateTwitterInMemoryTokenManager();

            var client = new TwitterClient(_tokenManager, Url.Action("TwitterCallback"));

            if (client.FinishAuthentication())
            {
                // Boom we are in, get the stuff we need
                //client.UserName;
                //client.AccessToken;
                //client.SecretToken;

                using (var unitOfWork = UnitOfWorkManager.NewUnitOfWork())
                {
                    var doCommit = true;

                    // See if the user has already logged in to this site using open Id
                    var user = MembershipService.GetUserByTwitterId(client.AccessToken);
                    var fakeEmail = string.Format("{0}@twitter.com", client.UserName);

                    if (user == null)
                    {
                        // First time logging in, so need to register them as new user
                        // password is irrelavant as they'll login using FB Id so generate random one

                        user = new MembershipUser
                        {
                            // Bit shit, but twitter won't give you an email. So we do this and
                            // Set notifications to false.
                            Email = fakeEmail,
                            Password = StringUtils.RandomString(8),
                            TwitterAccessToken = client.AccessToken,
                            IsExternalAccount = true,
                            DisableEmailNotifications = true,
                            UserName = _bannedWordService.SanitiseBannedWords(client.UserName),
                            Twitter = string.Format("http://twitter.com/{0}", _bannedWordService.SanitiseBannedWords(client.UserName))
                        };

                        doCommit = ProcessSocialLogonUser(user, doCommit);

                    }
                    else
                    {
                        // Do an update to make sure we have the most recent details
                        user.Email = fakeEmail;
                        user.MiscAccessToken = client.AccessToken;

                        TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                        {
                            Message = LocalizationService.GetResourceString("Members.NowLoggedIn"),
                            MessageType = GenericMessages.success
                        };

                        // Log the user in
                        FormsAuthentication.SetAuthCookie(user.UserName, true);
                    }

                    if (doCommit)
                    {
                        try
                        {
                            unitOfWork.Commit();
                            // Only send the email if the admin is not manually authorising emails or it's pointless
                            // CAN'T SENT TO TWITTER USERS AS WE DON'T HAVE AN EMAIL! :(
                            // https://dev.twitter.com/discussions/1737
                            //SendEmailConfirmationEmail(user);
                            return RedirectToAction("Index", "Home");
                        }
                        catch (Exception ex)
                        {
                            unitOfWork.Rollback();
                            LoggingService.Error(ex);
                            FormsAuthentication.SignOut();
                            TempData[AppConstants.MessageViewBagName] = new GenericMessageViewModel
                            {
                                Message = LocalizationService.GetResourceString("Errors.GenericMessage"),
                                MessageType = GenericMessages.error
                            };

                        }
                    }

                }

            }

            // Only add this if one hasn't been added already

MVCForum.Website/Controllers/PointController.cs
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class PointController : BaseController
    {
        private readonly IMembershipUserPointsService _membershipUserPointsService;

        public PointController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, 
            ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService,
            IMembershipUserPointsService membershipUserPointsService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _membershipUserPointsService = membershipUserPointsService;
        }

        [ChildActionOnly]
        [OutputCache(Duration = AppConstants.DefaultCacheLengthInSeconds)]
        public PartialViewResult CurrentWeekHighPointUsers()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var highEarners = _membershipUserPointsService.GetCurrentWeeksPoints(20);
                var viewModel = new HighEarnersPointViewModel { HighEarners = highEarners };
                return PartialView(viewModel);
            }
        }
    }
}

MVCForum.Website/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.DomainModel;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Utilities;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class SearchController : BaseController
    {
        private readonly IPostService _postService;
        private readonly ITopicService _topicsService;
        private readonly ILuceneService _luceneService;

        private MembershipUser LoggedOnUser;
        private MembershipRole UsersRole;

        public SearchController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, 
            IMembershipService membershipService, ILocalizationService localizationService, 
            IRoleService roleService, ISettingsService settingsService, 
            IPostService postService, ITopicService topicService, ILuceneService luceneService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _postService = postService;
            _topicsService = topicService;
            _luceneService = luceneService;

            LoggedOnUser = UserIsAuthenticated ? MembershipService.GetUser(Username) : null;
            UsersRole = LoggedOnUser == null ? RoleService.GetRole(AppConstants.GuestRoleName) : LoggedOnUser.Roles.FirstOrDefault();
        }

        [HttpGet]
        public ActionResult Index(int? p, string term)
        {
            if (!string.IsNullOrEmpty(term))
            {
                using (UnitOfWorkManager.NewUnitOfWork())
                {
                    // Set the page index
                    var pageIndex = p ?? 1;

                    // Returns the formatted string to search on
                    var formattedSearchTerm = StringUtils.ReturnSearchString(term);

                    // Get lucene to search
                    var luceneResults = _luceneService.Search(formattedSearchTerm, pageIndex, SettingsService.GetSettings().TopicsPerPage);


                    //// Get all the topics based on the search value
                    //var topics = _topicsService.SearchTopics(pageIndex,
                    //                                     SettingsService.GetSettings().TopicsPerPage,
                    //                                     AppConstants.ActiveTopicsListSize,
                    //                                     term);

                    var topics = _topicsService.GetTopicsByCsv(pageIndex, SettingsService.GetSettings().TopicsPerPage, AppConstants.ActiveTopicsListSize, luceneResults.Select(x => x.TopicId).ToList());

                    // Get all the categories for this topic collection
                    var categories = topics.Select(x => x.Category).Distinct();

                    // create the view model
                    var viewModel = new SearchViewModel
                    {
                        Topics = topics,
                        AllPermissionSets = new Dictionary<Category, PermissionSet>(),
                        PageIndex = pageIndex,
                        TotalCount = luceneResults.TotalCount,
                        Term = formattedSearchTerm
                    };

                    // loop through the categories and get the permissions
                    foreach (var category in categories)
                    {
                        var permissionSet = RoleService.GetPermissions(category, UsersRole);
                        viewModel.AllPermissionSets.Add(category, permissionSet);
                    }

                    return View(viewModel);
                } 
            }

            return RedirectToAction("Index", "Home");
        }


        [ChildActionOnly]
        public PartialViewResult SideSearch()
        {
            return PartialView();
        }

    }
}

MVCForum.Website/Controllers/TagController.cs
using System.Web.Mvc;
using MVCForum.Domain.Constants;
using MVCForum.Domain.Interfaces.Services;
using MVCForum.Domain.Interfaces.UnitOfWork;
using MVCForum.Website.ViewModels;

namespace MVCForum.Website.Controllers
{
    public class TagController : BaseController
    {
        private readonly ITopicTagService _topicTagService;

        public TagController(ILoggingService loggingService, IUnitOfWorkManager unitOfWorkManager, IMembershipService membershipService, ILocalizationService localizationService, IRoleService roleService, ISettingsService settingsService, ITopicTagService topicTagService)
            : base(loggingService, unitOfWorkManager, membershipService, localizationService, roleService, settingsService)
        {
            _topicTagService = topicTagService;
        }

        [ChildActionOnly]
        [OutputCache(Duration = AppConstants.DefaultCacheLengthInSeconds)]
        public PartialViewResult PopularTags()
        {
            using (UnitOfWorkManager.NewUnitOfWork())
            {
                var popularTags = _topicTagService.GetPopularTags(20);
                var viewModel = new PopularTagViewModel { PopularTags = popularTags };
                return PartialView(viewModel);
            }
        }

    }
}

MVCForum.Website/Views/Members/Edit.cshtml
@model MVCForum.Website.ViewModels.MemberFrontEndEditViewModel

@{
    ViewBag.Title = @Html.LanguageString("Members.EditProfile");
}
@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
     )  
}
@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
    @Html.Action("SideSearch", "Search")
    @Html.Action("PopularTags", "Tag")
    @Html.Action("CurrentWeekHighPointUsers", "Point")
}

@using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(x => Model.Id)

    @Html.ValidationSummary(false)
    
    <fieldset>
        <legend>@ViewBag.Title</legend>
        
        <p class="changepasswordtext">
            @Html.Raw(string.Format(Html.LanguageString("Members.ChangePassword.Link"), string.Format("<a href=\"{0}\">{1}</a>", Url.Action("ChangePassword"), Html.LanguageString("Members.ChangePassword.Title"))))
        </p>

        <div class="editor-label">
            @Html.LabelFor(x => x.UserName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.UserName)
            @Html.ValidationMessageFor(x => x.UserName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(x => x.Email)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Email)
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Age)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Age)
            @Html.ValidationMessageFor(x => x.Age)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Location)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Location)
            @Html.ValidationMessageFor(x => x.Location)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Website)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Website)
            @Html.ValidationMessageFor(x => x.Website)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Twitter)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Twitter)
            @Html.ValidationMessageFor(x => x.Twitter)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Facebook)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(x => x.Facebook)
            @Html.ValidationMessageFor(x => x.Facebook)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(x => x.Signature)
        </div>
        <div class="editor-field">
            @Html.EditorFor(x => x.Signature)
            @Html.ValidationMessageFor(x => x.Signature)
        </div>
        
        <div class="submit-holder">
            <input type="submit" class="btn btn-large btn-success" value="@Html.LanguageString("Buttons.Save")" />
        </div>
    </fieldset>
}


MVCForum.Website/Views/Members/ForgotPassword.cshtml
@model MVCForum.Website.ViewModels.ForgotPasswordViewModel

@{
    ViewBag.Title = Html.LanguageString("Members.ForgotPassword.Title");
}

@section Header
{
    @(
        Bundle.JavaScript()
            .Add("~/Scripts/jquery.validate.min.js")
            .Add("~/Scripts/jquery.validate.unobtrusive.min.js")            
            .MvcRender("~/scripts/cache/validate-combined_#.js")
    )
}

@using (Html.BeginForm("ForgotPassword", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    
    @Html.ValidationSummary(false)
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>@ViewBag.Title</legend>

        <div class="editor-label">
            @Html.LabelFor(m => m.EmailAddress)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.EmailAddress)
            @Html.ValidationMessageFor(m => m.EmailAddress)
        </div>

        <div class="submit-holder">
            <input type="submit" value="@Html.LanguageString("Buttons.ResetPassword")" class="btn btn-large btn-success" />
        </div>
    </fieldset>
    
}

MVCForum.Website/Views/Members/GetByName.cshtml
@using MVCForum.Domain.Constants
@using MVCForum.Utilities
@model MVCForum.Website.ViewModels.ViewMemberViewModel
@{
    ViewBag.Title = string.Concat(Model.User.UserName, Html.LanguageString("Members.ProfileTitle"));
}

@section Header
{
    <script type="text/javascript">
        $(function () {
            $.post(app_base + "Members/GetMemberDiscussions",
                { "Id": '@Model.User.Id' },
                function (data) {
                    $(".memberdiscussions").html(data);
                });
            TimeBadges();
        });
            function TimeBadges() {
                var timeBadgeViewModel = new Object();
                timeBadgeViewModel.Id = '@Model.User.Id';
            var strung = JSON.stringify(timeBadgeViewModel);
            $.ajax({
                url: app_base + 'Badge/Time',
                type: 'POST',
                dataType: 'html',
                data: strung,
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                },
                error: function (xhr, ajaxOptions, thrownError) {
                    ShowUserMessage("Error: " + xhr.status + " " + thrownError);
                }
            });
        }
    </script>
}

@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
    @Html.Action("SideSearch", "Search")
    @Html.Action("PopularTags", "Tag")
    @Html.Action("CurrentWeekHighPointUsers", "Point")
}

<div class="memberprofilepublic">

    <h2>@Model.User.UserName</h2>

    <div class="row-fluid">

        <div class="span3 memberavatardetails">
            <p><img src="@StringUtils.GetGravatarImage(Model.User.Email, AppConstants.GravatarProfileSize)" alt="@Model.User.UserName"></p>
            <p>@Html.LanguageString("Members.Profile.Joined") @Model.User.CreateDate.ToShortDateString()</p>
            <p>@Html.LanguageString("Members.Profile.Posts") @Model.User.Posts.Count</p>
            <p>@Html.LanguageString("Members.Profile.Points") @Model.User.TotalPoints</p>
            
            @if (User.Identity.IsAuthenticated && Model.User.UserName != User.Identity.Name)
            {
                <p><a href="@Url.Action("Create", "PrivateMessage", new { to = Model.User.Id }, null)" class="btn">@Html.LanguageString("Members.MessageMe")</a></p>
            }

            @if (User.Identity.IsAuthenticated && Html.Settings().EnableMemberReporting && Model.User.Id != Model.LoggedOnUserId)
            {
                <p><a href="@Url.Action("Report", "Members", new { id = Model.User.Id }, null)" class="btn">@Html.LanguageString("Buttons.Report")</a></p>
            }
                        
            @if (User.IsInRole(AppConstants.AdminRoleName) || User.IsInRole(AppConstants.ModeratorRoleName))
            {
                // Show whether this is a social account or not
                if (Convert.ToBoolean(Model.User.IsExternalAccount))
                {
                    <p>@Html.LanguageString("Members.Profile.IsSocialAccount")</p>    
                }
                
                // If this is an admins profile then do not show
                if (!Model.User.Roles.Any(x => x.RoleName.Contains(AppConstants.AdminRoleName)))
                {
                    <div class="memberprofileadminsection">
                        @Html.Partial("AdminMemberProfileTools")
                    </div>
                }
            }
        </div>

        <div class="span9 membermaindetails">

            <div class="row-fluid">
                <div class="span6 memberbio">

                    <p>@Html.LanguageString("Members.Profile.Age") @Html.Raw(Model.User.Age > 0 ? Model.User.Age.ToString() : "")</p>
                    <p>@Html.LanguageString("Members.Profile.Location") @Html.Raw(string.IsNullOrEmpty(Model.User.Location) ? "" : Model.User.Location)</p>
                    <p>@Html.LanguageString("Members.Profile.Website") @Html.Raw(string.IsNullOrEmpty(Model.User.Website) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Website))</p>
                    <p>@Html.LanguageString("Members.Profile.Twitter") @Html.Raw(string.IsNullOrEmpty(Model.User.Twitter) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Twitter))</p>
                    <p>@Html.LanguageString("Members.Profile.Facebook") @Html.Raw(string.IsNullOrEmpty(Model.User.Facebook) ? "" : string.Format("<a href='{0}' rel='nofollow'>{0}</a>", Model.User.Facebook))</p>
                </div>

                <div class="span6 memberlatesttopics">
                    <h3>@Html.LanguageString("Members.Profile.DiscussionActivity")</h3>
                    <div class="memberdiscussions">
                        <span class="ajaxspinner" title="@Html.LanguageString("Ajax.PleaseWait")">@Html.LanguageString("Ajax.PleaseWait")</span>
                    </div>
                </div>
            </div>

            <div class="row-fluid">
                <div class="span12 badgeactivity">
                    <h3>@Html.LanguageString("Members.Profile.Badges")</h3>
                    <div class="memberactivity">
                        @if (Model.User.Badges != null && Model.User.Badges.Any())
                        {
                            <ul class="memberbadgelist">
                                @foreach (var badge in Model.User.Badges)
                                {
                                    <li>
                                        <img src="@Url.Content(AppHelpers.ReturnBadgeUrl(badge.Image))" alt="@badge.Name" title="@badge.Name"/>
                                        @Html.Raw(badge.DisplayName)
                                    </li>
                                }
                            </ul>
                        }
                    </div>
                </div>
            </div>

            @if (User.IsInRole(AppConstants.AdminRoleName) || User.IsInRole(AppConstants.ModeratorRoleName))
            { 
                // Show the admin/mod notes on this user in case they are a spammer etc...
                <div class="row-fluid adminpublicomments">
                    <div class="span12">
                        @Html.Raw(Model.User.Comment)
                    </div>
                </div>   
            }

        </div>

    </div>

</div>

MVCForum.Website/Views/Members/GetMemberDiscussions.cshtml
@using MVCForum.Website.ViewModels
@model ViewMemberDiscussionsViewModel

@foreach (var topic in Model.Topics)
{
    // Get the permissions for this topic via its parent category
    var permissions = Model.AllPermissionSets[topic.Category];

    var viewModel = new ViewTopicViewModel { Permissions = permissions, Topic = topic, User = Model.CurrentUser, ShowCategoryName = false };
    Html.RenderPartial("_TopicSlim", viewModel);    
}

MVCForum.Website/Views/Members/Search.cshtml
@using MVCForum.Domain.Constants

@model MVCForum.Website.ViewModels.PublicMemberListViewModel
@{
    ViewBag.Title = Html.LanguageString("Members.SearchMembers");
}

@section side
{
    @Html.Action("ListCategorySideMenu", "Category")
    @Html.Action("SideSearch", "Search")
    @Html.Action("PopularTags", "Tag")
    @Html.Action("CurrentWeekHighPointUsers", "Point")
}


<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("Search", "Members", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="search large-search input-append">
        @Html.TextBoxFor(x => @Model.Search)
        <button class="btn">@Html.LanguageString("Buttons.Search")</button>
        @Html.HiddenFor(x => x.PageIndex)
    </div>
}

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>@Html.LanguageString("Members.Users")</th>
            <th>@Html.LanguageString("Members.Points")</th>
            <th>@Html.LanguageString("Members.DateJoined")</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>
                    <a href="@user.NiceUrl">@user.UserName</a>
                </td>
                <td>
                    @user.TotalPoints
                </td>
                <td>
                    @user.CreateDate.ToShortDateString()
                </td>
            </tr>
        }
    </tbody>
</table>

@if (Convert.ToInt32(Model.TotalCount) > AppConstants.AdminListPageSize)
{
    @Html.Pager(Convert.ToInt32(Model.PageIndex), AppConstants.AdminListPageSize, Convert.ToInt32(Model.TotalCount), new { search = Model.Search })
}

MVCForum.Website/Views/Members/SideAdminPanel.cshtml
@model MVCForum.Website.ViewModels.ViewAdminSidePanelViewModel
           
<div class="side-box profile-box">
    <h5>@Html.LanguageString("SideBox.MyTools")</h5>

    <ul>
        <li>
            <a href="@Url.Action("Edit", "Members", new { id = Model.CurrentUser.Id })">@Html.LanguageString("Buttons.Edit") @Model.CurrentUser.UserName</a>
        </li>

        @if(Html.Settings().EnablePrivateMessages && Model.CurrentUser.DisablePrivateMessages != true)
        {
            var count = Model.NewPrivateMessageCount <= 0 ? null : string.Format("({0})", Model.NewPrivateMessageCount);
            <li><a href="@Url.Action("Index", "PrivateMessage")">@Html.LanguageString("PM.PrivateMessages") @count</a></li>
        }

        <li>@Html.ActionLink(Html.LanguageString("Members.SearchMembers"), "Search", "Members")</li>
        <li>@Html.ActionLink(Html.LanguageString("LogOn.LogOff"), "LogOff", "Members")</li>
    </ul>
</div>